### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-json-schema#1]
See the [original issue](https://github.com/formly-js/angular-formly/issues/147)

**Comment by benoror** [comment]
+1

**Comment by panga** [comment]
+1

**Comment by mikeerickson** [comment]
+1

**Comment by kentcdodds** [comment]
+1 from me too. Anyone willing to implement it? I have no need of this in my project personally. And I'm too busy trying to keep up with angular-formly (and starting to look into Angular 2 for formly). So I'd happily let someone own this project if they want.

**Comment by benoror** [comment]
Not long before granting my heart to angular-formly, I used and played around with another awesome form-generation project which is heavily based on JSON schema called **[angular-schema-form](https://github.com/Textalk/angular-schema-form)**.

That being said, I believe most validation functionality in it is inherited from two dependencies: **[tv4](https://github.com/geraintluff/tv4)** and **[objectpath](https://github.com/mike-marcacci/objectpath)**.

Therefore I think efforts should not be duplicated, and leverage existing code by angular-schema-form folks (@davidlgj and @Dervisevic), who might point where to look at.

**Comment by luckylooke** [comment]
+1, I am in selection process and I cannot decide between angular-schema-form and angular-formly, but [benefit No.2 here](https://github.com/formly-js/angular-formly/issues/147#issuecomment-69198712) looks reasonable. :)

**Comment by kentcdodds** [comment]
@luckylooke, would you be interested in working on it? I would be happy to help get you/anyone going.

**Comment by luckylooke** [comment]
@kentcdodds I dont have time for it now, but I can also help someone who will be working on it.

**Comment by kentcdodds** [comment]
FYI to anyone who wants to do this, in [6.14.0](https://github.com/formly-js/angular-formly/blob/master/CHANGELOG.md#6140) I added a new feature called `fieldTransform` that should make this much easier.

**Comment by vicary** [comment]
With experience of using `angular-schema-form` there is a problem that people must build two schemas for most cases, because long forms are usually tabbed, sectioned and descriptive. IMO this cannot be directly transformed, at least users should be able to add more formly options after json-schema translation.

Maybe a merge mechanism would do, so people can separate data structure in json-schema for other purposes (mongoose translation or whatever) and build layout json for formly in another file.

**Comment by kentcdodds** [comment]
Having never used `json-schema` or `angular-schema-form`, I'm not sure of the best approach. But if you'd like to take it and run @vicary, I'd be more than happy to look at a PR :-)

**Comment by vicary** [comment]
The current situations is that [tv4](https://github.com/geraintluff/tv4) still has a bunch of issues regarding `$ref`, `oneOf` and `anyOf`. Which is why `angular-schema-form` is still kinda stuck in the middle of the pending-release of their own brew. IMO let's wait for a bit until it becomes stable.

**Comment by kentcdodds** [comment]
Sounds good. Thanks for the update. Maybe that's why angular-schema-form
has time to make funny ads for their library. They're waiting around for
updates to standards. ;-)

**Comment by pdufour** [comment]
Hi just wanted to see if anyone was working on this? I might be interested if no one has started yet.

**Comment by luckylooke** [comment]
@pdufour probably nobody ;)

**Comment by kentcdodds** [comment]
It's all yours :-)

**Comment by elyas-bhy** [comment]
@pdufour Any updates?

**Comment by pdufour** [comment]
Did not get started on this, ended up not using formly.

**Comment by suricactus** [comment]
Having json schema would be huge + of this project for people who want to be absolutely sure about the data and don't want to code it twice.
